export const getAllUsers = () => {
  return [
    {
      userId: "bla1",
      email: "carlos@g.com",
      name: "Carlos Alberto García Rosales",
      birthDate: "12-04-1997",
      phoneNumber: "939169253",
      photoUrl: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
      token: "blaBla",
      location: "Piura, Perú",
    },
    {
      userId: "bla2",
      email: "carlos@g.com",
      name: "Carlos Alberto García Rosales",
      birthDate: "12-04-1997",
      phoneNumber: "939169253",
      photoUrl: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
      token: "blaBla",
      location: "Piura, Perú",
    },
    {
      userId: "bla3",
      email: "carlos@g.com",
      name: "Carlos Alberto García Rosales",
      birthDate: "12-04-1997",
      phoneNumber: "939169253",
      photoUrl: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
      token: "blaBla",
      location: "Piura, Perú",
    },
    {
      userId: "bla4",
      email: "carlos@g.com",
      name: "Carlos Alberto García Rosales",
      birthDate: "12-04-1997",
      phoneNumber: "939169253",
      photoUrl: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
      token: "blaBla",
      location: "Piura, Perú",
    },
    {
      userId: "bla5",
      email: "carlos@g.com",
      name: "Carlos Alberto García Rosales",
      birthDate: "12-04-1997",
      phoneNumber: "939169253",
      photoUrl: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
      token: "blaBla",
      location: "Piura, Perú",
    },
  ];
};
